//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarGame.Web.WarGameServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WarGameServiceReference.IWarGameService")]
    public interface IWarGameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWarGameService/GetActiveCard", ReplyAction="http://tempuri.org/IWarGameService/GetActiveCardResponse")]
        WarGame.Transfer.ActiveCardDTO GetActiveCard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWarGameService/GetCardsLeft", ReplyAction="http://tempuri.org/IWarGameService/GetCardsLeftResponse")]
        byte GetCardsLeft();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWarGameService/RegisterUser", ReplyAction="http://tempuri.org/IWarGameService/RegisterUserResponse")]
        void RegisterUser(string username, string password, string firstname, string lastname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWarGameServiceChannel : WarGame.Web.WarGameServiceReference.IWarGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WarGameServiceClient : System.ServiceModel.ClientBase<WarGame.Web.WarGameServiceReference.IWarGameService>, WarGame.Web.WarGameServiceReference.IWarGameService {
        
        public WarGameServiceClient() {
        }
        
        public WarGameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WarGameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WarGameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WarGameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WarGame.Transfer.ActiveCardDTO GetActiveCard() {
            return base.Channel.GetActiveCard();
        }
        
        public byte GetCardsLeft() {
            return base.Channel.GetCardsLeft();
        }
        
        public void RegisterUser(string username, string password, string firstname, string lastname) {
            base.Channel.RegisterUser(username, password, firstname, lastname);
        }
    }
}
